### ISSUE TITLE
Event labels and command arguments do not permit the full set of legal values

### ISSUE THREAD

**Issue by duncathan** [nimblebun/tsc-language-server#2]
It appears that the language server currently enforces arguments being exactly 4 numbers. This is inconsistent with how TSC reads its numbers: 
```cpp
int GetTextScriptNo(const char* a)
{
	int b = 0;
	b += (a[0] - '0') * 1000;
	b += (a[1] - '0') * 100;
	b += (a[2] - '0') * 10;
	b += a[3] - '0';
	return b;
}
```

Many Cave Story mods make heavy usage of these non-numerical arguments for various reasons, and the language server displaying them as errors can be awfully annoying.

**Comment by jozsefsallai** [comment]
Hey!

Fair enough. I know the implementation is like that, I just thought it was enough to add support for numeric values and `<VAR` stuff only, as I haven't really seen anything outside of those being used in mods. If you could show me a practical example in which the language server would give a false warning, that would help me have a better understanding on the situation/need for it!

**Comment by duncathan** [comment]
In my randomizer, I make heavy usage of negative event labels in head.tsc (which are also perfectly legal and behave exactly as expected) in order to have more event space. Here's a very short snippet:
```
A==0, B==0 : S1=0, C=0
#0-00
<FL-4100<FLJ4201:0-01<FLJ4301:0-02<EVE0-10
A==1, B==0 : S1=1, C=0
#0-01
<FLJ4301:0-03<EVE0-10
A==0, B==1 : S1=1, C=0
#0-02
<FL+4201<EVE0-10
A==1, B==1 : S1=0, C=1
#0-03
<FL-4201<FL+4100<EVE0-10
```
Each of these <FLJ instructions throw a warning, because the language server is only seeing a single argument passed to it. Negative numbers in general have utility elsewhere: negative values can be used to decrease max HP (e.g. `<ML+000/`) and other such things. Additionally, a common advanced technique is to use out-of-bounds flags (flags outside the range of `0000`-`7999` inclusive) in order to read and write to other values in memory. For instance, `<FL+B816` can be used to set bit 0 of address 0x49e6ce, giving the player one active whimsical star following them.

**Comment by duncathan** [comment]
![image](https://user-images.githubusercontent.com/2979303/113495410-b366a100-94ae-11eb-80fa-2256da0381b2.png)
Here's a screenshot of it in vscode: you can see that I'm getting *a couple* false warnings, lol.

**Comment by jozsefsallai** [comment]
Thank you for describing the use case and for providing screenshots! I will do something about this.

**Comment by jozsefsallai** [comment]
I've added a [new tscrc option](https://docs.nimblebun.works/tscrc-json#setup-loose-checking) that changes the language server's behavior when validating event IDs and arguments:

```json
{
  "setup": {
    "looseChecking": {
      "events": true,
      "arguments": true
    }
  }
}
```

There is one small drawback to the loose option (but I don't think anyone would mind it much): Cave Story's TSC parser doesn't technically require you to use colon as an argument separator, that character space is completely ignored by the engine, so it can be any character. That behavior still persists in strict mode, but in loose mode, the language server expects that character to be a colon because the regular expression used for extracting TSC commands would parse too much stuff otherwise.

Currently there is no intent to change that behavior, as I'm wanting to create a library that would serve as a swiss-army knife for working with TSC files in Go and the language server will use that library in the long run. Creating such a library would also allow the existence of a TSC linter that can be used in CI, for example.

If you're fine with this approach and the possible drawback, let me know, so I can merge the PR and make a release. I will also update the Visual Studio Code extension to improve the syntax highlighter's behavior.

**Comment by duncathan** [comment]
Excellent! This should be plenty for my use case. 
On a related note, what's the process for overriding the tscrc option? I'm not totally familiar.

As for the drawback, using anything but a colon as a separator is nonstandard for sure. I'm aware of a handful of modders who have done so, but I'm not even sure if any of them are still active. I don't think it'll be of much concern in the interim, in any case.

**Comment by jozsefsallai** [comment]
Creating a file called `.tscrc.json` in the root of the workspace with the JSON from my previous comment should do the trick. I will run more thorough tests on the new feature and tag new releases later today!
